{
	"version": 1504530224,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/botão_oculos-sheet0.png",
		"images/botao_levelup-sheet0.png",
		"images/objeto-sheet0.png",
		"images/objeto3-sheet0.png",
		"images/oculos-sheet0.png",
		"images/animaçãocolocandooculos-sheet0.png",
		"images/animaçãocolocandooculos-sheet1.png",
		"images/botãodeóculos-sheet0.png",
		"images/mosca-sheet0.png",
		"images/muda_lado-sheet0.png",
		"images/chao-sheet0.png",
		"images/carrinho-sheet0.png",
		"images/carrinho-sheet1.png",
		"images/estante-sheet0.png",
		"images/carrinho2-sheet0.png",
		"images/carrinho3-sheet0.png",
		"images/cria_bloco-sheet0.png",
		"images/sensor_carrinho-sheet0.png",
		"images/cria_carrinho-sheet0.png",
		"images/porta-sheet0.png",
		"images/porta-sheet1.png",
		"images/botao_porta-sheet0.png",
		"images/robo-sheet0.png",
		"images/voltar-sheet0.png",
		"images/corpo_bomba-sheet0.png",
		"images/fio_amareloreal-sheet0.png",
		"images/fio_amareloreal-sheet1.png",
		"images/fio_vermelhoreal-sheet0.png",
		"images/fio_azulreal-sheet0.png",
		"images/estrelareal-sheet0.png",
		"images/estrelareal-sheet1.png",
		"images/luareal-sheet0.png",
		"images/solreal-sheet0.png",
		"images/rel_intriducao-sheet0.png",
		"images/rel_segestagio-sheet0.png",
		"images/rel_troll-sheet0.png",
		"images/rel_terestagio-sheet0.png",
		"images/rel_moscas-sheet0.png",
		"images/rel_robo-sheet0.png",
		"images/rel_bomba-sheet0.png",
		"images/fundo_menu-sheet0.png",
		"images/background_fim-sheet0.png",
		"images/background_fase4-sheet0.png",
		"images/background_fase6-sheet0.png",
		"images/background_creditos-sheet0.png",
		"images/particles_fios.png",
		"images/botao_vermelhoreal-sheet0.png",
		"images/botao_vermelhoreal-sheet1.png",
		"images/recipiente_bomba-sheet0.png",
		"images/background_fase1-sheet0.png",
		"images/objetos_sala-sheet0.png",
		"images/tv-sheet0.png",
		"images/tv-sheet1.png",
		"images/modulo_tv-sheet0.png",
		"images/botao_tv-sheet0.png",
		"images/porta_sala-sheet0.png",
		"images/fita1-sheet0.png",
		"images/fita2-sheet0.png",
		"images/fita3-sheet0.png",
		"images/fita4-sheet0.png",
		"images/fita5-sheet0.png",
		"images/background_fase2-sheet0.png",
		"images/background_fase3-sheet0.png",
		"images/background_fase7-sheet0.png",
		"images/objeto_menu1-sheet0.png",
		"images/logo-sheet0.png",
		"images/titulo-sheet0.png",
		"images/barra-sheet0.png",
		"images/intro_cartola-sheet0.png",
		"images/intro_cartola-sheet1.png",
		"images/intro_cartola-sheet2.png",
		"images/load-sheet0.png",
		"media/super_mario_bros_-coin_sound_effect.ogg",
		"media/mosquito (online-audio-converter.com).ogg",
		"media/áudio do robô.m4a",
		"media/áudio do robô.ogg",
		"media/tic da bomba (online-audio-converter.com).ogg",
		"media/seeking the truth.ogg",
		"media/suspense.ogg",
		"media/free_intro_epic_music_-_frantic_run_intro_a_-_4_se.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"bomba.mp4",
		"fitas ao longo das fases.mp4",
		"não acredite no que o doutor falar.mp4",
		"nunca olham para tras.mp4",
		"veja o som.mp4",
		"fim.mp4",
		"prológo.mp4",
		"fim.ogv",
		"nunca olham para tras.ogv",
		"prológo.ogv",
		"veja o som.ogv",
		"fitas ao longo das fases.ogv",
		"não acredite no que o doutor falar.ogv",
		"bomba.ogv",
		"fim.webm",
		"prológo.webm",
		"nunca_olham_para_tras.webm",
		"bomba.webm",
		"veja o som.webm",
		"não acredite no que o doutor falar.webm",
		"fitas ao longo das fases.webm"
	]
}